apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: aegis-data
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: aegis
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: redis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redis
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        command:
          - redis-server
          - "/redis-master/redis.conf"
        env:
        - name: MASTER
          value: "true"
        ports:
        - containerPort: 6379
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        volumeMounts:
        - mountPath: /redis-master
          name: config
      volumes:
        - name: config
          configMap:
            name: redis-config
            items:
            - key: redis.conf
              path: redis.conf
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: aegis-data
data:
  redis.conf: |
    maxmemory 256mb
    maxmemory-policy allkeys-lru
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: aegis-data
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app.kubernetes.io/name: redis
