"""README integrity gate.

The README is generated by eval/generate_readme.py from committed result
files.  These tests fail if anyone hand-edits README.md, if the template or
generator drifts from the committed README, or if any numeric token in the
README can no longer be traced to a committed source.

Skipped when README.md does not yet exist or when running under the
generator's own live pytest invocation (AEGIS_README_BUILDING=1), which is
producing the README that these tests would verify.
"""
import os
import subprocess
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[2]
README = ROOT / "README.md"


def _bootstrap_needed() -> bool:
    return os.environ.get("AEGIS_README_BUILDING") == "1" or not README.exists()


def _run(cmd: list) -> subprocess.CompletedProcess:
    return subprocess.run(cmd, cwd=ROOT, capture_output=True, text=True, timeout=600)


def test_readme_matches_template_and_sources():
    if _bootstrap_needed():
        pytest.skip("README.md not generated yet (bootstrap build in progress)")
    r = _run([sys.executable, "eval/generate_readme.py", "--check"])
    assert r.returncode == 0, (
        "README.md is out of date with docs/README.template.md + result files; "
        "run `make readme`.\n" + (r.stdout + r.stderr)[-4000:]
    )


def test_every_number_in_readme_traces_to_sources():
    if _bootstrap_needed():
        pytest.skip("README.md not generated yet (bootstrap build in progress)")
    r = _run([sys.executable, "eval/check_report_numbers.py", "--readme"])
    assert r.returncode == 0, (
        "README.md contains numbers not derivable from the committed result files.\n"
        + (r.stdout + r.stderr)[-4000:]
    )
